config/routes.rb
Bank::Application.routes.draw do
  devise_for :users

  resources :users
  resources :movimentations, only: [:new]
  resources :extracts, only: [:new, :index]
  resources :entries, only: [:new, :create]
  resources :deposits, only: [:new, :create]
  resources :transfers, only: [:new, :create]
  root "home#index"

end

app/models/transfer.rb
class Transfer
  include ActiveModel::Model
  attr_accessor :account_id, :account_destiny_id, :quantity

  validates_presence_of :account_destiny_id
  validates_presence_of :account_id
  validates_presence_of :quantity
  validates_numericality_of :quantity, greater_than: 0

  validate :valid_account_destiny_id

  def valid_account_destiny_id
    errors.add(:account_destiny_id, 'Conta destino não pode ser a conta de origem') if account_id.eql?(account_destiny_id)
  end

  def operation
    'transfer'
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  layout 'home'
  before_action :load_account

  def new
    @transfer = Transfer.new
    respond_with @transfer
  end

  def create
    @transfer = Transfer.new params[:transfer]
    if @transfer.valid?
      transfer_service = TransferService.new @transfer
      flash[:messge] = 'Transferência efetuada.' if transfer_service.run
    end
    respond_with @transfer, location: root_path
  end

  private

  def movimentation_params
    params.require(:movimentation).permit(:quantity, :operation)
  end
end

app/views/transfers/new.html.slim
h5 = show_title 'Transferência'
= simple_form_for @transfer, url: transfers_path do |f|
  = f.input :account_id, as: :hidden, input_html: { value: current_user.account.id }
  = f.error_notification

  .form-inputs
    = f.input :quantity, label: 'Valor', class: 'fix-input', placeholder: 'Valor', \
      required: true
    = f.input :account_destiny_id, placeholder: 'Conta p/ transferência', \
      label: 'Conta destino', required: true

    = f.button :submit, 'Transferir', class: 'btn btn-info'

hr
.transfer-info
  h5 = 'Informações sobre transferência: '
  ul
    li = 'De segunda a sexta das 9 às 18 horas a taxa é 5 reais por transferência'
    li = 'Fora desse horário a taxa é 7 reais'
    li = 'Acima de 1000 reais há um adicional de 10 reais na taxa'