config/routes.rb
Bank::Application.routes.draw do
  devise_for :users

  resources :users
  resources :movimentations, only: [:new]
  resources :extracts, only: [:new, :index]
  resources :entries, only: [:new, :create]
  resources :deposits, only: [:new, :create]
  resources :transfers, only: [:new, :create]
  root "home#index"

end

app/views/layouts/application.html.slim
html
  head
    title MiniBank
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  body
    #container
      = show_flash(flash)
      = yield

app/views/layouts/home.html.slim
html
  head
    title MiniBank
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  body
    #container
      .navbar.navbar-fixed-top.navbar-static-top
        .navbar-inner
          .container.nav-collapsecollapse
            = link_to 'My Bank', '#', class: 'brand'
            .pull-right
              ul.nav.pull-right
                li = link_to "Olá #{current_user.name}", '#'
                li.divider
                li = link_to 'Logout', destroy_user_session_path, \
                  method: :delete, data: { confirm: 'Deseja sair ?' }
      .span3
        .sidebar-nav
          .well
            ul.nav.nav-list
              li.nav-header = 'Ações'
              li = link_to 'Início', root_path
              li = link_to 'Saques', new_entry_path
              li = link_to 'Depósitos', new_deposit_path
              li = link_to 'Transferências', new_transfer_path
              li = link_to 'Extratos', new_extract_path
              li = link_to 'Editar Dados', edit_user_path(current_user)
              li = link_to 'Cancelar Conta', registration_path(current_user), \
                data: { confirm: 'Quer realmente apagar a sua conta ?' }, \
                method: :delete
      .span6.well
        .pull-right
          span = "Seu saldo é: <span class='label label-success'>#{to_real(current_user.account_total)}</span>".html_safe
          br
        hr
        = yield
  footer
    .container
      .row-fluid
        .span6
          p Powered with Thrash Metal, Coca-Cola, Ruby on Rails & Bootstrap !
        .span6
          p Deployed with Capistrano